### PR TITLE
build fails due to invalid ig id: change myig.xml id to hl7.fhir.uv.myig

### PR DESCRIPTION
**Pull request by Healthedata1**

### CODE REVIEW

**Comment by lmckenzi** [comment]
It *shouldn't* fail - this isn't an HL7 IG...

**Comment by lmckenzi** [comment]
I just genned the IG and there was no QA error and no failure?

**Comment by Healthedata1** [comment]
what template did you use?  I used the HL7 one.

Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by lmckenzi** [comment]
Sample-ig is not an HL7 IG.  It's not going to build with the HL7 template, just the base template.  (We can discuss whether there's a value in having a separate HL7 sample that imposes the additional rules, though my leaning is just to have a page in the 'guidance' IG that highlights the additional changes and perhaps point to that from sample.

**Comment by Healthedata1** [comment]
OK ... is their an example IG for HL7 guides?

Eric

Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by lmckenzi** [comment]
No, not yet - thus my question and my suggestion

**Comment by lmckenzi** [comment]
This seems to no longer be relevant.  Re-submit if you think something still needs to be done with the sample-ig

**Pull request closed without merging**
